# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.4

# Default target executed when no arguments are given to make.
default_target: all

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/siegerstein/admin/lang/libsml

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/siegerstein/admin/lang/libsml

# Include the progress variables for this target.
include CMakeFiles/progress.make

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/siegerstein/admin/lang/libsml/CMakeFiles $(CMAKE_ALL_PROGRESS)
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/siegerstein/admin/lang/libsml/CMakeFiles 0

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean

# The main clean target
clean/fast: clean

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1

#=============================================================================
# Target rules for targets named sml

# Build rule for target.
sml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sml

# fast build rule for target.
sml/fast:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/build

# target to build an object file
src/SML/Audio/Audio.o:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/Audio.o

# target to preprocess a source file
src/SML/Audio/Audio.i:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/Audio.i

# target to generate assembly for a file
src/SML/Audio/Audio.s:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/Audio.s

# target to build an object file
src/SML/Audio/Codec/DecodedData.o:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/Codec/DecodedData.o

# target to preprocess a source file
src/SML/Audio/Codec/DecodedData.i:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/Codec/DecodedData.i

# target to generate assembly for a file
src/SML/Audio/Codec/DecodedData.s:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/Codec/DecodedData.s

# target to build an object file
src/SML/Audio/Codec/WAV/WAV.o:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/Codec/WAV/WAV.o

# target to preprocess a source file
src/SML/Audio/Codec/WAV/WAV.i:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/Codec/WAV/WAV.i

# target to generate assembly for a file
src/SML/Audio/Codec/WAV/WAV.s:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/Codec/WAV/WAV.s

# target to build an object file
src/SML/Audio/PAI.o:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/PAI.o

# target to preprocess a source file
src/SML/Audio/PAI.i:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/PAI.i

# target to generate assembly for a file
src/SML/Audio/PAI.s:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/PAI.s

# target to build an object file
src/SML/Audio/SoundSystem/ALSA/DSP/ALSA_DSP.o:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/SoundSystem/ALSA/DSP/ALSA_DSP.o

# target to preprocess a source file
src/SML/Audio/SoundSystem/ALSA/DSP/ALSA_DSP.i:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/SoundSystem/ALSA/DSP/ALSA_DSP.i

# target to generate assembly for a file
src/SML/Audio/SoundSystem/ALSA/DSP/ALSA_DSP.s:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/SoundSystem/ALSA/DSP/ALSA_DSP.s

# target to build an object file
src/SML/Audio/SoundSystem/OSS/DSP/OSS_DSP.o:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/SoundSystem/OSS/DSP/OSS_DSP.o

# target to preprocess a source file
src/SML/Audio/SoundSystem/OSS/DSP/OSS_DSP.i:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/SoundSystem/OSS/DSP/OSS_DSP.i

# target to generate assembly for a file
src/SML/Audio/SoundSystem/OSS/DSP/OSS_DSP.s:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/SoundSystem/OSS/DSP/OSS_DSP.s

# target to build an object file
src/SML/Audio/SoundSystem/OSS/Mixer/OSS_Mixer.o:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/SoundSystem/OSS/Mixer/OSS_Mixer.o

# target to preprocess a source file
src/SML/Audio/SoundSystem/OSS/Mixer/OSS_Mixer.i:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/SoundSystem/OSS/Mixer/OSS_Mixer.i

# target to generate assembly for a file
src/SML/Audio/SoundSystem/OSS/Mixer/OSS_Mixer.s:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/SoundSystem/OSS/Mixer/OSS_Mixer.s

# target to build an object file
src/SML/Audio/SoundSystem/SoundSystemManager.o:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/SoundSystem/SoundSystemManager.o

# target to preprocess a source file
src/SML/Audio/SoundSystem/SoundSystemManager.i:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/SoundSystem/SoundSystemManager.i

# target to generate assembly for a file
src/SML/Audio/SoundSystem/SoundSystemManager.s:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Audio/SoundSystem/SoundSystemManager.s

# target to build an object file
src/SML/Utils/Base64/Base64.o:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Utils/Base64/Base64.o

# target to preprocess a source file
src/SML/Utils/Base64/Base64.i:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Utils/Base64/Base64.i

# target to generate assembly for a file
src/SML/Utils/Base64/Base64.s:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Utils/Base64/Base64.s

# target to build an object file
src/SML/Utils/Func/Func.o:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Utils/Func/Func.o

# target to preprocess a source file
src/SML/Utils/Func/Func.i:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Utils/Func/Func.i

# target to generate assembly for a file
src/SML/Utils/Func/Func.s:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/Utils/Func/Func.s

# target to build an object file
src/SML/config.o:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/config.o

# target to preprocess a source file
src/SML/config.i:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/config.i

# target to generate assembly for a file
src/SML/config.s:
	$(MAKE) -f CMakeFiles/sml.dir/build.make CMakeFiles/sml.dir/src/SML/config.s

# Help Target
help::
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sml"
	@echo "... src/SML/Audio/Audio.o"
	@echo "... src/SML/Audio/Audio.i"
	@echo "... src/SML/Audio/Audio.s"
	@echo "... src/SML/Audio/Codec/DecodedData.o"
	@echo "... src/SML/Audio/Codec/DecodedData.i"
	@echo "... src/SML/Audio/Codec/DecodedData.s"
	@echo "... src/SML/Audio/Codec/WAV/WAV.o"
	@echo "... src/SML/Audio/Codec/WAV/WAV.i"
	@echo "... src/SML/Audio/Codec/WAV/WAV.s"
	@echo "... src/SML/Audio/PAI.o"
	@echo "... src/SML/Audio/PAI.i"
	@echo "... src/SML/Audio/PAI.s"
	@echo "... src/SML/Audio/SoundSystem/ALSA/DSP/ALSA_DSP.o"
	@echo "... src/SML/Audio/SoundSystem/ALSA/DSP/ALSA_DSP.i"
	@echo "... src/SML/Audio/SoundSystem/ALSA/DSP/ALSA_DSP.s"
	@echo "... src/SML/Audio/SoundSystem/OSS/DSP/OSS_DSP.o"
	@echo "... src/SML/Audio/SoundSystem/OSS/DSP/OSS_DSP.i"
	@echo "... src/SML/Audio/SoundSystem/OSS/DSP/OSS_DSP.s"
	@echo "... src/SML/Audio/SoundSystem/OSS/Mixer/OSS_Mixer.o"
	@echo "... src/SML/Audio/SoundSystem/OSS/Mixer/OSS_Mixer.i"
	@echo "... src/SML/Audio/SoundSystem/OSS/Mixer/OSS_Mixer.s"
	@echo "... src/SML/Audio/SoundSystem/SoundSystemManager.o"
	@echo "... src/SML/Audio/SoundSystem/SoundSystemManager.i"
	@echo "... src/SML/Audio/SoundSystem/SoundSystemManager.s"
	@echo "... src/SML/Utils/Base64/Base64.o"
	@echo "... src/SML/Utils/Base64/Base64.i"
	@echo "... src/SML/Utils/Base64/Base64.s"
	@echo "... src/SML/Utils/Func/Func.o"
	@echo "... src/SML/Utils/Func/Func.i"
	@echo "... src/SML/Utils/Func/Func.s"
	@echo "... src/SML/config.o"
	@echo "... src/SML/config.i"
	@echo "... src/SML/config.s"



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0

